# Environment
@hosturl = http://localhost:4000
@authToken =
@xTenantId = local

### 1. Authorization (id is the persona, roles is a comma separated list)
GET {{hosturl}}/authorization/admin?roles=ADMIN_ADMIN,SUPER_ADMIN
Authorization: Bearer {{authToken}}
x-tenant-id: {{xTenantId}}
